### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by mitcheguevara**
JESSA Oh JESSA, why are you a bully?

### CODE REVIEW

**Comment by preese13** [comment]
yeah, why are you a bully????

**Comment by jessamarie** [comment]
@preese13 stay out of this!

**Comment by preese13** [comment]
I'm not just gonna sit back and let you bully Mitche!!!!!!!!!!!!! what kind of person would I be?

**Comment by mitcheguevara** [comment]
Thank you!

**Comment by jessamarie** [comment]
@preese13 I'm being framed.

**Comment by preese13** [comment]
Fair warning: I will be monitoring your github account for future wrongdoing aimed at your peers

**Comment by jessamarie** [comment]
Good thing I have no history anyway!

**Comment by preese13** [comment]
Sad to see the history and culture of our great country being ripped apart with the erasing of Jessa's past comments. You can't change history, but you can learn from it. Robert E Lee, Stonewall Jackson - who's next, Washington, Jefferson? So foolish! Also, the beauty that is being taken out of our cities, towns and parks will be greatly missed and never able to be comparably replaced!

**Comment by jessamarie** [comment]
I don't get how my non-existent (or ever-existing) past comments compare to the history of our great & beautiful America.

**Comment by mitcheguevara** [comment]
the aggressor never gets it.

**Comment by lizardbird** [comment]
Be the change you wish to see in the world Jessa. Be the change.

**Comment by jessamarie** [comment]
@preese13 and @mitcheguevara are playing a cruel, cruel joke on me.

**Comment by preese13** [comment]
We need change!  Study what General Pershing of the United States did to terrorists when caught. There was no more Radical Islamic Terror for 35 years!

**Comment by jessamarie** [comment]
@preese13 I am actually aware of this event, believe it or not.

**Comment by mitcheguevara** [comment]
I am the victim here!

**Comment by jessamarie** [comment]
@mitcheguevara you can blame me all you want, but what your really doing is projecting.

**Comment by mitcheguevara** [comment]
Everyday I come in and the first thing you say to me is, " Oh, I thought you dropped out?"

**Comment by jessamarie** [comment]
@mitcheguevara Yes, but with a tone of relief which typically means "I'm so glad you didn't drop out!"

And, not to play the victim here, but when everyone was calling me the 'cursed one,' what did you say? Hmm?

**Comment by mitcheguevara** [comment]
@jessamarie I sat next to you in hopes of breaking the curse, and thanks I get is a daily reminder!

**Comment by preese13** [comment]
Mitche, dont worry!  Military solutions are now fully in place,locked and loaded,should she act unwisely.  Hopefully Jess will find another path!

**Comment by jessamarie** [comment]
@mitcheguevara If you told me that it hurt your feelings, I would have stopped. Communication is the KEY!

**Comment by preese13** [comment]
Then it is good we have cleared the air.  We can finally move forward.  After 200 days, rarely has any Administration achieved what we have achieved..not even close! Don't believe the Fake News Suppression Polls!

**Comment by preese13** [comment]
Jessa, I am now willing to accept your apology on behalf of Mitche

**Comment by jessamarie** [comment]
@preese13 I would like Mitche to accept my sincere apology on behalf of Mitche

**Comment by preese13** [comment]
He has asked me to accept the apology on his behalf as he is still afraid of you.

**Comment by mitcheguevara** [comment]
Mitche on behalf of Mitche? I think a chicken biscuit is in order for tomorrow morning!

**Comment by lizardbird** [comment]
Make that 2 chicken biscuits

**Comment by jessamarie** [comment]
@mitcheguevara NO, NO PLEASE NOT MY CHICKEN BISCUIT.

**Comment by jessamarie** [comment]
I BEG OF YOU ANYTHING ELSE PLEASE.

**Comment by mitcheguevara** [comment]
I wants it, I want the precious! 
https://media.tenor.com/images/236ee382fdf16973567dc3bb44c21b51/tenor.gif

**Comment by kadkins4** [comment]
Hello? is this thing on?

**Comment by preese13** [comment]
kendall! how are you?

**Pull request closed without merging**
